### PR TITLE
fix: leaderboard get route had a limit of 3 on query

### PR DESCRIPTION
**Pull request by tyleryy**

### CODE REVIEW

**Comment by NwinNwin** [comment]
We want to first 3 users in leaderboard to avoid having all emails expose to the public

**Comment by tyleryy** [comment]
Should we have two routes? one for retrieving all users and one for only top 3?

**Comment by NwinNwin** [comment]
Cureently  we dont have any use case to retieve all users in leaderboard

**Comment by tyleryy** [comment]
Ah kk sg. Feel free to close then.

**Pull request closed without merging**
